INSERT INTO Clients(id, name, lastName, email, createdAt, photo) VALUES(1, 'ivan', 'hdz', 'prueba@mail.com', '2017-01-01','');
INSERT INTO Clients(id, name, lastName, email, createdAt, photo) VALUES(2, 'ivan2', 'hdz', 'prueba@mail.com', '2017-01-01','');
INSERT INTO Clients(id, name, lastName, email, createdAt, photo) VALUES(3, 'ivan', 'hdz', 'prueba@mail.com', '2017-01-01','');
/**INSERT INTO Clients(id, name, lastName, email, createdAt) VALUES(4, 'ivan2', 'hdz', 'prueba@mail.com', '2017-01-01');
INSERT INTO Clients(id, name, lastName, email, createdAt) VALUES(5, 'ivan', 'hdz', 'prueba@mail.com', '2017-01-01');
INSERT INTO Clients(id, name, lastName, email, createdAt) VALUES(6, 'ivan2', 'hdz', 'prueba@mail.com', '2017-01-01');
INSERT INTO Clients(id, name, lastName, email, createdAt) VALUES(7, 'ivan', 'hdz', 'prueba@mail.com', '2017-01-01');
INSERT INTO Clients(id, name, lastName, email, createdAt) VALUES(8, 'ivan2', 'hdz', 'prueba@mail.com', '2017-01-01');
INSERT INTO Clients(id, name, lastName, email, createdAt) VALUES(9, 'ivan2', 'hdz', 'prueba@mail.com', '2017-01-01');
INSERT INTO Clients(id, name, lastName, email, createdAt) VALUES(10, 'ivan2', 'hdz', 'prueba@mail.com', '2017-01-01');
INSERT INTO Clients(id, name, lastName, email, createdAt) VALUES(11, 'ivan2', 'hdz', 'prueba@mail.com', '2017-01-01');
INSERT INTO Clients(id, name, lastName, email, createdAt) VALUES(12, 'ivan2', 'hdz', 'prueba@mail.com', '2017-01-01');
INSERT INTO Clients(id, name, lastName, email, createdAt) VALUES(13, 'ivan2', 'hdz', 'prueba@mail.com', '2017-01-01');
INSERT INTO Clients(id, name, lastName, email, createdAt) VALUES(14, 'ivan2', 'hdz', 'prueba@mail.com', '2017-01-01');
INSERT INTO Clients(id, name, lastName, email, createdAt) VALUES(15, 'ivan2', 'hdz', 'prueba@mail.com', '2017-01-01');
INSERT INTO Clients(id, name, lastName, email, createdAt) VALUES(16, 'ivan2', 'hdz', 'prueba@mail.com', '2017-01-01');
INSERT INTO Clients(id, name, lastName, email, createdAt) VALUES(17, 'ivan2', 'hdz', 'prueba@mail.com', '2017-01-01');
INSERT INTO Clients(id, name, lastName, email, createdAt) VALUES(18, 'ivan2', 'hdz', 'prueba@mail.com', '2017-01-01');
INSERT INTO Clients(id, name, lastName, email, createdAt) VALUES(19, 'ivan2', 'hdz', 'prueba@mail.com', '2017-01-01');
INSERT INTO Clients(id, name, lastName, email, createdAt) VALUES(20, 'ivan2', 'hdz', 'prueba@mail.com', '2017-01-01');
INSERT INTO Clients(id, name, lastName, email, createdAt) VALUES(21, 'ivan2', 'hdz', 'prueba@mail.com', '2017-01-01');
INSERT INTO Clients(id, name, lastName, email, createdAt) VALUES(22, 'ivan2', 'hdz', 'prueba@mail.com', '2017-01-01');
INSERT INTO Clients(id, name, lastName, email, createdAt) VALUES(23, 'ivan2', 'hdz', 'prueba@mail.com', '2017-01-01');
INSERT INTO Clients(id, name, lastName, email, createdAt) VALUES(24, 'ivan2', 'hdz', 'prueba@mail.com', '2017-01-01');
INSERT INTO Clients(id, name, lastName, email, createdAt) VALUES(25, 'ivan2', 'hdz', 'prueba@mail.com', '2017-01-01');
INSERT INTO Clients(id, name, lastName, email, createdAt) VALUES(26, 'ivan2', 'hdz', 'prueba@mail.com', '2017-01-01');
INSERT INTO Clients(id, name, lastName, email, createdAt) VALUES(27, 'ivan2', 'hdz', 'prueba@mail.com', '2017-01-01');
INSERT INTO Clients(id, name, lastName, email, createdAt) VALUES(28, 'ivan2', 'hdz', 'prueba@mail.com', '2017-01-01');
INSERT INTO Clients(id, name, lastName, email, createdAt) VALUES(29, 'ivan2', 'hdz', 'prueba@mail.com', '2017-01-01');
INSERT INTO Clients(id, name, lastName, email, createdAt) VALUES(30, 'ivan2', 'hdz', 'prueba@mail.com', '2017-01-01');
INSERT INTO Clients(id, name, lastName, email, createdAt) VALUES(31, 'ivan2', 'hdz', 'prueba@mail.com', '2017-01-01');
INSERT INTO Clients(id, name, lastName, email, createdAt) VALUES(32, 'ivan2', 'hdz', 'prueba@mail.com', '2017-01-01');
INSERT INTO Clients(id, name, lastName, email, createdAt) VALUES(33, 'ivan2', 'hdz', 'prueba@mail.com', '2017-01-01');
INSERT INTO Clients(id, name, lastName, email, createdAt) VALUES(34, 'ivan2', 'hdz', 'prueba@mail.com', '2017-01-01');
INSERT INTO Clients(id, name, lastName, email, createdAt) VALUES(35, 'ivan2', 'hdz', 'prueba@mail.com', '2017-01-01');**/